### ISSUE TITLE
grub老师出问题

### ISSUE THREAD

**Issue by ledewrt** [garypang13/Actions-OpenWrt-Snapshot-With-Nginx#3]
ga大，最近几次都是在grub处出错。我换19.07也是这样。：
Makefile:79: WARNING: skipping grub2 -- package has no install section
Makefile:80: *** Package/grub2-editenv is missing the TITLE field.  Stop.
make[3]: Leaving directory '/home/runner/work/lede-stable/lede-stable/lede/package/boot/grub2'
time: package/boot/grub2/host-compile#0.15#0.04#0.19
make[2]: *** [package/boot/grub2/host/compile] Error 2
package/Makefile:111: recipe for target 'package/boot/grub2/host/compile' failed
make[1]: *** [/home/runner/work/lede-stable/lede-stable/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[2]: Leaving directory '/home/runner/work/lede-stable/lede-stable/lede'
make: *** [world] Error 2
package/Makefile:107: recipe for target '/home/runner/work/lede-stable/lede-stable/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: Leaving directory '/home/runner/work/lede-stable/lede-stable/lede'
/home/runner/work/lede-stable/lede-stable/lede/include/toplevel.mk:225: recipe for target 'world' failed

地址：https://github.com/ledewrt/lede-stable/runs/535163410?check_suite_focus=true
实属无招了。特想向求助。你空了帮忙看下。

**Comment by garypang13** [comment]
你的.config文件应该是从以前老的版本复制过来的,比如CONFIG_LINUX_4_14=y,实际上应该是CONFIG_LINUX_5.4=y了
我的建议是自定义.config文件中只添加自己需要的明白其具体作用的内容.其他内容make defconfig会自动生成的.这样维护起来更方便且不容易出错.

**Comment by ledewrt** [comment]
不是这个问题，我找到原因了。固件的uefi那个插件有问题。得注释掉才行。
